AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Demo1ContactForm1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::148849141066:role/service-role/Bitrix24Lambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /Demo1ContactForm1
            Method: ANY
      Environment:
        Variables:
          Region: us-east-1
          Table: Demo1Form2
